import { Question } from "./types";

export const ASSESSMENT_QUESTIONS: Question[] = [
  // =========================================================================
  // SECTION 1: PSYCHOLOGICAL TEMPERAMENT & EMOTIONAL REGULATION
  // =========================================================================
  {
    id: "psy_01_frustration",
    category: "psychological_temperament",
    categoryTitle: "Psychological Temperament & Emotional Regulation",
    categoryTitleEs: "Temperamento Psicológico y Regulación Emocional",
    question: "You have spent 45 minutes preparing lunch, but the 3-year-old pushes the bowl away, screams 'Yucky!', and throws the spoon onto the floor. How do you internally react and what do you do?",
    questionEs: "Has pasado 45 minutos preparando el almuerzo, pero el niño de 3 años empuja el plato, grita '¡Qué asco!' y tira la cuchara al suelo. ¿Cómo reaccionas internamente y qué haces?",
    context: "Measures emotional regulation, impulse control, and frustration tolerance when personal effort is rejected.",
    contextEs: "Evalúa la regulación emocional, el control de impulsos y la tolerancia a la frustración ante el rechazo.",
    type: "single_choice",
    options: [
      {
        id: "psy_01_a",
        text: "I take a deep breath to regulate myself, calmly say 'You don’t have to eat it, but food stays on the table', remove the plate without anger, and offer a neutral alternative later.",
        textEs: "Respiro hondo para regularme, digo con calma: 'No tienes que comerlo, pero la comida se queda en la mesa', retiro el plato sin enojo y más tarde ofrezco una opción neutra.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "psy_01_b",
        text: "I feel somewhat irritated because I worked hard, but I tell the child they won't get any treats until they finish every bite of what I made.",
        textEs: "Me siento algo irritada porque me esforcé, pero le digo al niño que no tendrá golosinas hasta que coma todo lo que cociné.",
        score: 5,
        isRedFlag: false,
      },
      {
        id: "psy_01_c",
        text: "I immediately put the child in time-out for disrespecting my effort and making a mess.",
        textEs: "Pongo al niño inmediatamente en tiempo fuera por faltarle el respeto a mi esfuerzo y hacer desorden.",
        score: 3,
        isRedFlag: false,
      },
      {
        id: "psy_01_d",
        text: "I raise my voice firmly so they understand they crossed the line; toddlers must learn to respect adults.",
        textEs: "Alzo la voz con firmeza para que entienda que cruzó la línea; los niños pequeños deben aprender a respetar a los adultos.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Prone to anger escalation and punitive reaction over normal developmental toddler behavior.",
        redFlagReasonEs: "Tendencia a escalar en enojo y reaccionar de forma punitiva ante una conducta normal del desarrollo de un niño pequeño.",
      },
    ],
    idealAnswerExplanation: "A 3-year-old child's prefrontal cortex is still developing. Testing boundaries with food is normal. The caregiver must remain an emotional anchor rather than taking developmental pushback personally.",
    idealAnswerExplanationEs: "La corteza prefrontal de un niño de 3 años aún está madurando. Probar límites con la comida es normal. Quien cuida debe ser un ancla emocional y no tomar la conducta como una ofensa personal.",
    psychologicalInsight: "Evaluates emotional stability and non-reactivity. High-scoring candidates regulate their nervous system before engaging the child.",
    psychologicalInsightEs: "Evalúa estabilidad emocional y no reactividad. Las mejores candidatas regulan primero su sistema nervioso antes de intervenir.",
    followUpInterviewQuestion: "Can you recall a time a child completely rejected your effort? How did your emotional state evolve over that hour?",
    followUpInterviewQuestionEs: "¿Recuerdas alguna ocasión en que un niño rechazó por completo tu esfuerzo? ¿Cómo evolucionó tu estado emocional durante esa hora?",
  },
  {
    id: "psy_02_tantrum_public",
    category: "psychological_temperament",
    categoryTitle: "Psychological Temperament & Emotional Regulation",
    categoryTitleEs: "Temperamento Psicológico y Regulación Emocional",
    question: "The 3-year-old throws an intense, loud meltdown on the ground at a crowded park because it's time to go home. Strangers are staring at you. What is your primary psychological priority?",
    questionEs: "El niño de 3 años tiene una rabieta muy intensa tirado en el suelo de un parque concurrido porque es hora de volver a casa. La gente se queda mirando. ¿Cuál es tu prioridad psicológica principal?",
    context: "Measures social anxiety vs. child-centered attunement and patience under social pressure.",
    contextEs: "Mide la presión social frente a la conexión empática y paciencia centrada en el niño.",
    type: "single_choice",
    options: [
      {
        id: "psy_02_a",
        text: "Stay completely grounded, ignore onlookers, ensure the child is physically safe, get down to their eye level, validate their sadness, and calmly wait for the storm to pass before moving.",
        textEs: "Mantenerme en calma, ignorar las miradas ajenas, asegurar que el niño esté a salvo, ponerme a su altura, validar su tristeza y esperar con serenidad a que pase la tormenta antes de avanzar.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "psy_02_b",
        text: "Quickly promise them ice cream or let them watch a video on my phone just to stop the screaming so we don't disturb others.",
        textEs: "Prometerle rápido un helado o prestarle mi celular con un video solo para que deje de gritar y no incomodar a la gente.",
        score: 4,
        isRedFlag: false,
      },
      {
        id: "psy_02_c",
        text: "Physically yank the child up and carry them away while reprimanding them for embarrassing me in public.",
        textEs: "Jalonear físicamente al niño hacia arriba y llevármelo cargado regañándolo por ponerme en vergüenza en público.",
        score: 1,
        isRedFlag: true,
        redFlagReason: "Displays ego-centric embarrassment and physical roughness when under public scrutiny.",
        redFlagReasonEs: "Muestra vergüenza egocéntrica y brusquedad física al estar bajo la mirada pública.",
      },
      {
        id: "psy_02_d",
        text: "Walk a few steps away and pretend I don't know the child until they get tired of crying.",
        textEs: "Alejarme unos pasos y fingir que no conozco al niño hasta que se canse de llorar.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Severe safety neglect and psychological abandonment trigger for a toddler.",
        redFlagReasonEs: "Grave negligencia de seguridad y detonante de abandono psicológico para un niño de 3 años.",
      },
    ],
    idealAnswerExplanation: "A 3-year-old melting down cannot process logic. The caregiver's role is co-regulation: staying calm, keeping them safe, and letting them know their big emotions are manageable.",
    idealAnswerExplanationEs: "En plena rabieta, un niño de 3 años no procesa la lógica. El rol de la cuidadora es la co-regulación: mantener la calma, proteger su seguridad y transmitirle que sus emociones son manejables.",
    psychologicalInsight: "High emotional security caregivers do not allow bystander judgment to compromise their warmth and safety protocols.",
    psychologicalInsightEs: "Las cuidadoras con seguridad emocional no permiten que el juicio de terceros comprometa su calidez y protocolos de protección.",
    followUpInterviewQuestion: "How do you feel when strangers stare at you during a child's meltdown? What mental self-talk do you use?",
    followUpInterviewQuestionEs: "¿Cómo te sientes cuando desconocidos te miran fijamente durante el berrinche de un niño? ¿Qué te dices a ti misma internamente?",
  },
  {
    id: "psy_03_repetitive_stress",
    category: "psychological_temperament",
    categoryTitle: "Psychological Temperament & Emotional Regulation",
    categoryTitleEs: "Temperamento Psicológico y Regulación Emocional",
    question: "The child asks 'Why?' over 50 times in 20 minutes, interrupts your phone handover, and repeats the same question even after you explained it 5 times. Which describes your honest emotional state?",
    questionEs: "El niño pregunta '¿Por qué?' más de 50 veces en 20 minutos, interrumpe y repite la misma pregunta incluso después de haberle explicado 5 veces. ¿Cuál describe tu estado emocional real?",
    context: "Measures tolerance for sensory monotony, patience, and child curiosity appreciation.",
    contextEs: "Mide la tolerancia a la monotonía sensorial, la paciencia y el aprecio por la curiosidad infantil.",
    type: "single_choice",
    options: [
      {
        id: "psy_03_a",
        text: "I genuinely enjoy their inquisitiveness. I might playfully reflect the question back ('Why do YOU think the sky is blue?') or redirect to an interactive experiment.",
        textEs: "Disfruto sinceramente su curiosidad. Suelo devolverle la pregunta con juego ('¿Por qué crees TÚ que el cielo es azul?') o redirigir hacia un experimento interactivo.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "psy_03_b",
        text: "It gets a little tiring, so I gently tell them 'We've talked about this, let's take a quiet rest for our ears now'.",
        textEs: "Me resulta un poco agotador, así que le digo suavemente: 'Ya platicamos de esto, vamos a darle un descansito a nuestras orejas'.",
        score: 8,
        isRedFlag: false,
      },
      {
        id: "psy_03_c",
        text: "I tune them out and stop answering after the 5th time.",
        textEs: "Me desconecto mentalmente y dejo de responder después de la quinta vez.",
        score: 4,
        isRedFlag: false,
      },
      {
        id: "psy_03_d",
        text: "I snap or sternly tell them to stop talking because it feels like deliberate torment.",
        textEs: "Le llamo la atención bruscamente y le ordeno que se calle porque siento que lo hace para fastidiar.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Projects hostile intent onto benign developmental toddler inquisitiveness.",
        redFlagReasonEs: "Proyecta intención hostil sobre la curiosidad natural del desarrollo del niño pequeño.",
      },
    ],
    idealAnswerExplanation: "At age 3, 'Why?' is how children connect and build neural pathways, not an interrogation. A patient nanny treats curiosity with warmth.",
    idealAnswerExplanationEs: "A los 3 años, el '¿Por qué?' es la vía del niño para conectar y crear sinapsis, no un interrogatorio. Una niñera paciente acoge la curiosidad con ternura.",
    psychologicalInsight: "Differentiates caregivers who view child behavior as malicious or taxing vs. those who view it as a developmental window.",
    psychologicalInsightEs: "Diferencia entre cuidadoras que perciben la conducta infantil como maliciosa vs. aquellas que la ven como una ventana de desarrollo.",
    followUpInterviewQuestion: "When you feel your energy draining on a long day, what boundary do you set with yourself to prevent snapping?",
    followUpInterviewQuestionEs: "Cuando sientes que tu energía se agota en un día largo, ¿qué límite te pones a ti misma para no perder los estribos?",
  },

  // =========================================================================
  // SECTION 2: CRITICAL SAFETY, CPR & EMERGENCY PREPAREDNESS
  // =========================================================================
  {
    id: "safe_01_choking_prevention",
    category: "safety_and_emergency",
    categoryTitle: "Critical Safety, CPR & Emergency Protocols",
    categoryTitleEs: "Seguridad Crítica, RCP y Protocolos de Emergencia",
    question: "Which of the following food preparation methods is REQUIRED to prevent fatal airway obstruction in a 3-year-old?",
    questionEs: "¿Cuál de los siguientes métodos de preparación de alimentos es OBLIGATORIO para prevenir la asfixia por obstrucción de vía aérea en un niño de 3 años?",
    context: "Pediatric choking risk assessment (AAP & Red Cross guidelines).",
    contextEs: "Evaluación de riesgo de atragantamiento pediátrico (Guías de la AAP y Cruz Roja).",
    type: "single_choice",
    options: [
      {
        id: "safe_01_a",
        text: "Grapes, cherry tomatoes, and hot dogs must be sliced lengthwise (quartered into long thin sticks), and whole nuts, raw popcorn, and hard candies must not be given.",
        textEs: "Uvas, tomates cherry y salchichas deben cortarse a lo largo (en cuartos como palitos delgados), y nunca dar nueces enteras, palomitas de maíz ni caramelos duros.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "safe_01_b",
        text: "Grapes and cherry tomatoes can be served whole as long as the child sits still and is told to chew carefully.",
        textEs: "Las uvas y tomates cherry se pueden dar enteros siempre que el niño esté sentado y se le diga que mastique con cuidado.",
        score: 1,
        isRedFlag: true,
        redFlagReason: "Fails basic pediatric choking prevention; round spherical foods can completely seal the toddler trachea.",
        redFlagReasonEs: "Incumple la prevención básica de atragantamiento; los alimentos esféricos pueden sellar por completo la tráquea infantil.",
      },
      {
        id: "safe_01_c",
        text: "Cutting hot dogs into round coin slices is sufficient safety preparation.",
        textEs: "Cortar las salchichas en rodajas redondas como monedas es preparación suficiente.",
        score: 2,
        isRedFlag: true,
        redFlagReason: "Round coin slices of hot dogs are one of the most common causes of toddler asphyxiation.",
        redFlagReasonEs: "Las rodajas redondas de salchicha son una de las causas más frecuentes de asfixia mortal en niños pequeños.",
      },
      {
        id: "safe_01_d",
        text: "Food preparation doesn't matter as long as I watch them while they eat.",
        textEs: "La forma de cortar la comida no importa mientras los observe mientras comen.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Severe misunderstanding of choking mechanics and pediatric safety.",
        redFlagReasonEs: "Desconocimiento grave de la mecánica de atragantamiento y seguridad pediátrica.",
      },
    ],
    idealAnswerExplanation: "The American Academy of Pediatrics states that foods the size and shape of a child's airway (uncut grapes, coin-cut hot dogs, whole nuts) are lethal hazards. Lengthwise quartering is essential.",
    idealAnswerExplanationEs: "La Academia Americana de Pediatría señala que los alimentos con el diámetro de la vía aérea de un niño son mortales. Es indispensable el corte longitudinal en cuartos.",
    psychologicalInsight: "Demonstrates rigorous vigilance and actual working knowledge of pediatric emergency prevention.",
    psychologicalInsightEs: "Demuestra conocimiento real y vigilancia preventiva en emergencias pediátricas.",
    followUpInterviewQuestion: "Walk me through how you prepare an afternoon snack plate for a 3-year-old from start to finish.",
    followUpInterviewQuestionEs: "Cuéntame paso a paso cómo preparas un plato de merienda para un niño de 3 años de principio a fin.",
  },
  {
    id: "safe_02_water_safety",
    category: "safety_and_emergency",
    categoryTitle: "Critical Safety, CPR & Emergency Protocols",
    categoryTitleEs: "Seguridad Crítica, RCP y Protocolos de Emergencia",
    question: "The 3-year-old is in the bathtub with 4 inches of warm water. The parent's doorbell rings with an urgent courier package. What do you do?",
    questionEs: "El niño de 3 años está en la bañera con 10 cm de agua tibia. Suena el timbre con un paquete urgente de paquetería. ¿Qué haces?",
    context: "Bath & water vigilance standards.",
    contextEs: "Normas de vigilancia en agua y baño.",
    type: "single_choice",
    options: [
      {
        id: "safe_02_a",
        text: "Never leave the child unattended for even one second. Either wrap the child in a towel and take them with me to the door, or let the courier leave the package.",
        textEs: "Jamás dejar al niño solo ni por un segundo. Envuelvo al niño en una toalla y lo llevo conmigo a la puerta, o dejo que el repartidor se vaya.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "safe_02_b",
        text: "Step out for just 15 seconds to grab the package quickly while telling the child to sit completely still.",
        textEs: "Salir solo 15 segundos a recoger el paquete rápido diciéndole al niño que no se mueva del lugar.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Critical safety hazard: Toddlers can drown silently in 1-2 inches of water in under 30 seconds.",
        redFlagReasonEs: "Peligro mortal crítico: Un niño pequeño puede ahogarse en silencio en menos de 30 segundos con solo 3 cm de agua.",
      },
      {
        id: "safe_02_c",
        text: "Stand in the hallway with the bathroom door open so I can listen for splashes while opening the front door.",
        textEs: "Quedarme en el pasillo con la puerta del baño abierta para escuchar si chapotea mientras abro la puerta principal.",
        score: 1,
        isRedFlag: true,
        redFlagReason: "Drowning is silent; children do not splash or yell when their airway is submerged.",
        redFlagReasonEs: "El ahogamiento es silencioso; los niños no chapotean ni gritan cuando su vía respiratoria se sumerge.",
      },
      {
        id: "safe_02_d",
        text: "Tell the courier through the window to wait until bath time is finished in 10 minutes, leaving child in bath.",
        textEs: "Gritarle al repartidor por la ventana que espere 10 minutos a que termine el baño, dejando al niño en el agua.",
        score: 2,
        isRedFlag: true,
        redFlagReason: "Distraction while child is unattended in water.",
        redFlagReasonEs: "Distracción peligrosa mientras el niño permanece desatendido en el agua.",
      },
    ],
    idealAnswerExplanation: "Touch supervision in water is non-negotiable. Toddler drowning is 100% silent and rapid. No package or phone call warrants stepping away.",
    idealAnswerExplanationEs: "La supervisión al tacto en el agua es innegociable. El ahogamiento de niños pequeños es 100% silencioso y veloz. Ninguna llamada o entrega justifica apartarse.",
    psychologicalInsight: "Vigilance and adherence to protocol even under competing minor distractions.",
    psychologicalInsightEs: "Vigilancia e inviolabilidad de protocolos de seguridad ante distracciones cotidianas.",
    followUpInterviewQuestion: "What is your strict protocol around pools, bathtubs, and open bodies of water when caring for a toddler?",
    followUpInterviewQuestionEs: "¿Cuál es tu protocolo estricto alrededor de piscinas, bañeras y fuentes de agua al cuidar a un niño pequeño?",
  },
  {
    id: "safe_03_head_injury",
    category: "safety_and_emergency",
    categoryTitle: "Critical Safety, CPR & Emergency Protocols",
    categoryTitleEs: "Seguridad Crítica, RCP y Protocolos de Emergencia",
    question: "The child trips on the living room rug, hits their forehead on the coffee table corner, cries hard, and develops a small red bump ('goose egg'). They stop crying after 5 minutes and want to play. What is your action?",
    questionEs: "El niño tropieza con la alfombra de la sala, se golpea la frente contra la esquina de la mesa de centro, llora con fuerza y le sale un chichón rojo. A los 5 minutos deja de llorar y quiere jugar. ¿Qué haces?",
    context: "Emergency assessment, concussion observation, and parent communication transparency.",
    contextEs: "Evaluación de traumatismo, observación de conmoción y transparencia en la comunicación con los padres.",
    type: "single_choice",
    options: [
      {
        id: "safe_03_a",
        text: "Apply a cold compress wrapped in cloth, inspect for pupils/wounds, notify parents immediately with a photo and call, monitor closely for vomiting/lethargy, and document exact time and symptoms.",
        textEs: "Aplicar compresa fría envuelta en paño, revisar pupilas y heridas, avisar de inmediato a los padres con foto y llamada, monitorear vómitos/letargo y anotar hora exacta y síntomas.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "safe_03_b",
        text: "Put ice on it and don't tell the parents right away to avoid worrying them at work, unless it swells bigger by evening.",
        textEs: "Ponerle hielo y no avisar a los papás enseguida para no preocuparlos en el trabajo, a menos que se hinche más hacia la tarde.",
        score: 2,
        isRedFlag: true,
        redFlagReason: "Concealing a head trauma from parents compromises child safety and indicates lack of transparency.",
        redFlagReasonEs: "Ocultar un golpe en la cabeza a los padres compromete la salud del menor y demuestra falta de transparencia.",
      },
      {
        id: "safe_03_c",
        text: "Give the child children's ibuprofen immediately from the cabinet without checking with parents.",
        textEs: "Darle ibuprofeno infantil del botiquín de inmediato sin consultar previamente a los padres.",
        score: 2,
        isRedFlag: true,
        redFlagReason: "Administering unauthorized medication without explicit parental consent.",
        redFlagReasonEs: "Administración de medicamentos sin autorización médica o consentimiento expreso de los padres.",
      },
      {
        id: "safe_03_d",
        text: "Since they stopped crying, it's just a regular bump. I will only mention it at handover if the parents ask about the red mark.",
        textEs: "Como ya no llora, fue solo un golpe común. Solo lo mencionaré al final de la jornada si los padres preguntan por la marca roja.",
        score: 1,
        isRedFlag: true,
        redFlagReason: "Lack of proactive communication and failure to monitor for delayed head injury symptoms.",
        redFlagReasonEs: "Falta de comunicación proactiva y omisión en la vigilancia de síntomas tardíos de traumatismo craneal.",
      },
    ],
    idealAnswerExplanation: "Any blow to the head requires immediate parental notification, cold compress, and ongoing neurological observation (alertness, pupil symmetry, gait). Caregivers must never hide incidents.",
    idealAnswerExplanationEs: "Cualquier golpe en la cabeza exige notificación inmediata a los padres, frío local y vigilancia neurológica (alerta, pupilas, marcha). Una cuidadora jamás debe ocultar un incidente.",
    psychologicalInsight: "Measures honesty, integrity, and proactive incident escalation without fear of blame.",
    psychologicalInsightEs: "Mide honestidad, integridad y escalamiento de incidentes sin temor al reproche.",
    followUpInterviewQuestion: "Tell me about a real accident or spill that happened under your supervision in a previous family. How and when did you tell the parents?",
    followUpInterviewQuestionEs: "Cuéntame de algún accidente o caída real que ocurrió bajo tu cuidado en una familia anterior. ¿Cómo y cuándo se lo comunicaste a los padres?",
  },

  // =========================================================================
  // SECTION 3: TODDLER DEVELOPMENT (AGE 3) & DAILY CARE
  // =========================================================================
  {
    id: "dev_01_potty_accident",
    category: "toddler_development_age3",
    categoryTitle: "Toddler Behavior & Age-3 Developmental Care",
    categoryTitleEs: "Conducta y Desarrollo Infantil a los 3 Años",
    question: "A 3-year-old child is mostly potty trained, but while deeply engaged in building Lego blocks, they have a wet accident on the rug. How do you respond?",
    questionEs: "Un niño de 3 años casi domina el orinal, pero mientras juega muy concentrado armando piezas de Lego, tiene un accidente y moja la alfombra. ¿Cómo respondes?",
    context: "Measures developmental awareness of regression and shame-free toileting philosophy.",
    contextEs: "Evalúa comprensión del desarrollo de regresión y filosofía de control de esfínteres libre de culpa o castigo.",
    type: "single_choice",
    options: [
      {
        id: "dev_01_a",
        text: "Warmly and matter-of-factly say: 'Accidents happen when you are playing so hard! Let’s get dry clothes and clean up together.' Never shame or scold.",
        textEs: "Con calidez y tranquilidad digo: '¡Los accidentes pasan cuando juegas con tantas ganas! Vamos por ropa seca y limpiamos juntos'. Jamás avergonzar ni regañar.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "dev_01_b",
        text: "Say: 'You are a big boy now, big boys don’t pee their pants! You should have listened when I reminded you.'",
        textEs: "Decirle: '¡Ya eres un niño grande, los niños grandes no se hacen encima! Debiste hacerme caso cuando te recordé'.",
        score: 3,
        isRedFlag: false,
      },
      {
        id: "dev_01_c",
        text: "Make them sit on the toilet for 20 minutes as a reminder to go next time.",
        textEs: "Sentarlo en el inodoro durante 20 minutos como castigo para que recuerde ir la próxima vez.",
        score: 1,
        isRedFlag: true,
        redFlagReason: "Punitive toileting causes urinary retention, anxiety, and long-term potty training regression.",
        redFlagReasonEs: "El control punitivo de esfínteres causa retención urinaria, ansiedad y regresión severa.",
      },
      {
        id: "dev_01_d",
        text: "Take away their Lego blocks for the rest of the day because they ignored their body cues.",
        textEs: "Quitarle los bloques de Lego por el resto del día por haber ignorado las señales de su cuerpo.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Unrelated punitive consequences that harm cognitive and emotional trust.",
        redFlagReasonEs: "Castigos desvinculados de la situación que perjudican el vínculo y la confianza emocional.",
      },
    ],
    idealAnswerExplanation: "At age 3, intense play suppresses interoceptive cues (bladder fullness). Shaming causes anxiety and withholding. Compassionate, non-punitive cleanup supports healthy autonomy.",
    idealAnswerExplanationEs: "A los 3 años el juego absorbe la atención del niño sobre sus señales corporales. La vergüenza genera retención y miedo. La limpieza acompañada y sin reproches consolida la autonomía.",
    psychologicalInsight: "Attitude toward developmental imperfection. Differentiates nurturing teachers from punitive enforcers.",
    psychologicalInsightEs: "Actitud ante la imperfección infantil. Separa a las cuidadoras educadoras de las vigilantes punitivas.",
    followUpInterviewQuestion: "What is your philosophy on supporting potty training without pressure or shaming?",
    followUpInterviewQuestionEs: "¿Cuál es tu método para acompañar el control de esfínteres sin presiones ni reproches?",
  },
  {
    id: "dev_02_screen_time_play",
    category: "toddler_development_age3",
    categoryTitle: "Toddler Behavior & Age-3 Developmental Care",
    categoryTitleEs: "Conducta y Desarrollo Infantil a los 3 Años",
    question: "It is a rainy afternoon, and the parents have a strict 'No Screen Time' rule for their 3-year-old. The child is restless and whining. What is your go-to activity plan?",
    questionEs: "Es una tarde de lluvia y los padres tienen una regla estricta de 'Cero Pantallas' para su hijo de 3 años. El niño está inquieto y quejumbroso. ¿Cuál es tu plan de actividades?",
    context: "Creativity, engagement, and initiative in child-directed play.",
    contextEs: "Creatividad, proactividad e iniciativa en el juego infantil guiado.",
    type: "single_choice",
    options: [
      {
        id: "dev_02_a",
        text: "Create an indoor obstacle course with cushions, do an interactive sensory play with shaving cream or playdough, read stories with funny character voices, and build a blanket fort.",
        textEs: "Crear un circuito de obstáculos con cojines, armar un juego sensorial con plastilina o masa, leer cuentos cambiando voces de personajes y armar un fuerte con cobijas.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "dev_02_b",
        text: "Put on an educational documentary on YouTube on my iPad since educational content doesn't really count as bad screen time.",
        textEs: "Ponerle un documental educativo en YouTube en mi tableta porque lo educativo no cuenta realmente como pantalla dañina.",
        score: 2,
        isRedFlag: true,
        redFlagReason: "Directly violates family rules and rationalizes breaking boundaries.",
        redFlagReasonEs: "Viola frontalmente las reglas del hogar y justifica saltarse los acuerdos de la familia.",
      },
      {
        id: "dev_02_c",
        text: "Put the child in their room with their toys and tell them to play independently for 2 hours.",
        textEs: "Meter al niño a su habitación con sus juguetes y decirle que juegue solo durante 2 horas.",
        score: 3,
        isRedFlag: false,
      },
      {
        id: "dev_02_d",
        text: "Give them drawing paper and then check my personal phone while they color.",
        textEs: "Darle hojas para colorear y aprovechar para revisar mi celular mientras dibuja.",
        score: 2,
        isRedFlag: false,
      },
    ],
    idealAnswerExplanation: "A 3-year-old requires active engagement, gross motor outlets, and imaginative play on indoor days. Respecting parental boundaries regarding screens is essential.",
    idealAnswerExplanationEs: "Un niño de 3 años necesita movimiento corporal y juego imaginativo en días de encierro. El respeto absoluto a los límites de pantallas acordados por la familia es vital.",
    psychologicalInsight: "Energy investment and imaginative pedagogical capacity.",
    psychologicalInsightEs: "Capacidad lúdica, iniciativa y respeto a los valores familiares.",
    followUpInterviewQuestion: "What are three engaging sensory or motor activities you love doing with 3-year-olds on rainy days?",
    followUpInterviewQuestionEs: "¿Cuáles son tres actividades sensoriales o motrices que te encanta realizar con niños de 3 años en días lluviosos?",
  },
  {
    id: "dev_03_hitting_defiance",
    category: "toddler_development_age3",
    categoryTitle: "Toddler Behavior & Age-3 Developmental Care",
    categoryTitleEs: "Conducta y Desarrollo Infantil a los 3 Años",
    question: "When told it is nap time, the 3-year-old looks you in the eye, shouts 'You are stupid!', and hits your thigh with their small hand. What is your exact response?",
    questionEs: "Cuando le dices que es hora de la siesta, el niño de 3 años te mira a los ojos, grita '¡Eres tonta!' y te da un manotazo en el muslo. ¿Cuál es tu respuesta exacta?",
    context: "Setting safe boundaries with emotional regulation; de-escalating physical aggression without aggression.",
    contextEs: "Poner límites seguros con calma; desescalar la agresión física sin recurrir a la violencia.",
    type: "single_choice",
    options: [
      {
        id: "dev_03_a",
        text: "Gently hold their wrist/hands: 'I won't let you hit me. Hitting hurts. You are really mad that it is nap time. It is hard to stop playing. Let's take 3 big dragon breaths together.'",
        textEs: "Sostengo sus manitas con suavidad: 'No te permitiré pegarme. Pegar duele. Estás muy molesto porque es hora de dormir y cuesta dejar de jugar. Respiremos juntos como dragones'.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "dev_03_b",
        text: "Swat their hand back lightly so they learn how it feels, and say 'How do you like that?'",
        textEs: "Darle un manotazo de vuelta para que sienta lo que se siente y decirle: '¿A que no te gusta?'",
        score: 0,
        isRedFlag: true,
        redFlagReason: "ZERO TOLERANCE: Engaging in reciprocal physical hitting or retaliation against a toddler.",
        redFlagReasonEs: "TOLERANCIA CERO: Responder con agresión física recíproca o represalia corporal hacia un niño.",
      },
      {
        id: "dev_03_c",
        text: "Laugh it off and treat it as cute, then give them a cookie to calm down.",
        textEs: "Reírme de la situación como si fuera graciosa y darle una galleta para calmarlo.",
        score: 3,
        isRedFlag: false,
      },
      {
        id: "dev_03_d",
        text: "Yell 'Don't you ever dare touch me!' and shut them in their bedroom alone.",
        textEs: "Gritarle '¡No te atrevas a tocarme jamás!' y encerrarlo solo en su recámara.",
        score: 1,
        isRedFlag: true,
        redFlagReason: "Hostile emotional outbursts and isolating punitive behavior.",
        redFlagReasonEs: "Explosión emocional violenta y aislamiento punitivo traumático para un niño pequeño.",
      },
    ],
    idealAnswerExplanation: "Gentle firmness stops the physical behavior ('I won't let you hit') while validating the underlying emotion. Physical retaliation of any kind is an immediate disqualifier.",
    idealAnswerExplanationEs: "La firmeza respetuosa frena la agresión física sin dañar, al tiempo que valida la emoción de base. La represalia física es motivo inmediato de descalificación.",
    psychologicalInsight: "Impulse control, boundary holding, and non-violent communication.",
    psychologicalInsightEs: "Control de impulsos, sostenimiento de límites y comunicación no violenta.",
    followUpInterviewQuestion: "Have you ever had a child physically hit or bite you? How did you de-escalate without losing composure?",
    followUpInterviewQuestionEs: "¿Alguna vez un niño te ha pegado o mordido? ¿Cómo desescalaste la situación sin perder la compostura?",
  },

  // =========================================================================
  // SECTION 4: ETHICS, PROFESSIONALISM & HOUSEHOLD BOUNDARIES
  // =========================================================================
  {
    id: "eth_01_smartphone_policy",
    category: "ethics_and_professionalism",
    categoryTitle: "Ethics, Professional Boundaries & Reliability",
    categoryTitleEs: "Ética, Límites Profesionales y Confiabilidad",
    question: "What is your standard practice regarding smartphone and social media usage while on duty caring for a 3-year-old child?",
    questionEs: "¿Cuál es tu práctica habitual respecto al uso del teléfono inteligente y redes sociales mientras estás en horario de trabajo cuidando al niño de 3 años?",
    context: "Distraction risks, child privacy, and professional ethics.",
    contextEs: "Riesgos de distracción, privacidad del menor y ética profesional.",
    type: "single_choice",
    options: [
      {
        id: "eth_01_a",
        text: "My phone stays in my bag/pocket on vibrate for parent calls only. I never browse social media or text friends while supervising. I never post photos of the child anywhere online without explicit written permission.",
        textEs: "Mi celular permanece en mi bolso/bolsillo en vibrador solo para llamadas de los padres. Jamás navego en redes ni chateo con amigos en horas de servicio. Nunca publico fotos del niño en internet.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "eth_01_b",
        text: "I check messages and social media when the child is playing nicely by themselves nearby.",
        textEs: "Reviso mensajes y redes sociales de vez en cuando si el niño está jugando tranquilo cerca de mí.",
        score: 3,
        isRedFlag: false,
      },
      {
        id: "eth_01_c",
        text: "I take cute TikToks or Instagram stories of our fun activities to share with my followers, but I don't show the street address.",
        textEs: "Grabo TikToks o historias de Instagram bonitas de nuestras actividades para mis seguidores, pero sin mostrar la dirección de la casa.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Severe privacy breach and digital safety risk for the child.",
        redFlagReasonEs: "Violación grave de la privacidad y riesgo para la seguridad digital del menor.",
      },
      {
        id: "eth_01_d",
        text: "I keep wireless earbuds in one ear listening to podcasts while watching the child at the playground.",
        textEs: "Uso un audífono inalámbrico en una oreja escuchando podcasts mientras vigilo al niño en el parque.",
        score: 3,
        isRedFlag: false,
      },
    ],
    idealAnswerExplanation: "Toddlers require continuous situational awareness; split-second accidents occur when eyes are on screens. Digital privacy of minors is an absolute parental right.",
    idealAnswerExplanationEs: "Los niños de 3 años requieren atención auditiva y visual continua. Los accidentes ocurren en segundos al mirar pantallas. La privacidad digital de un menor es derecho exclusivo de los padres.",
    psychologicalInsight: "Focus, discipline, and respect for family privacy standards.",
    psychologicalInsightEs: "Capacidad de concentración, disciplina y respeto por la intimidad familiar.",
    followUpInterviewQuestion: "How do you manage your personal communications and digital boundaries during an 8-hour workday?",
    followUpInterviewQuestionEs: "¿Cómo manejas tus comunicaciones personales y tus límites digitales durante una jornada laboral de 8 horas?",
  },
  {
    id: "eth_02_discipline_alignment",
    category: "ethics_and_professionalism",
    categoryTitle: "Ethics, Professional Boundaries & Reliability",
    categoryTitleEs: "Ética, Límites Profesionales y Confiabilidad",
    question: "You have personal beliefs about how children should be disciplined that differ from the family's guidelines (e.g., parents practice authoritative positive parenting, but you grew up believing in strict punishments). How do you handle this?",
    questionEs: "Tienes creencias personales sobre la crianza que difieren de las normas de la familia (ej. los padres practican crianza respetuosa, pero tú creciste con castigos severos). ¿Cómo manejas esto?",
    context: "Adaptability and alignment with parental authority in their home.",
    contextEs: "Capacidad de adaptación y alineación con la autoridad de los padres en su hogar.",
    type: "single_choice",
    options: [
      {
        id: "eth_02_a",
        text: "I respect that the parents set the values in their home. I commit to executing their parenting philosophy consistently and ask clarifying questions so we are a unified team.",
        textEs: "Respeto que los padres definen los valores en su hogar. Me comprometo a aplicar su filosofía con consistencia y hago preguntas para trabajar como un equipo alineado.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "eth_02_b",
        text: "I agree with the parents to their face, but when they leave for work I use my own strict methods because I know what works better.",
        textEs: "Les digo que sí de frente, pero en cuanto se van a trabajar aplico mis propios métodos estrictos porque sé mejor lo que funciona.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Deceitful conduct, subverting parental authority, and breach of trust.",
        redFlagReasonEs: "Conducta desleal, sabotaje de la autoridad parental y traición a la confianza del hogar.",
      },
      {
        id: "eth_02_c",
        text: "I constantly debate with the parents each morning about why their approach is too soft.",
        textEs: "Debato continuamente con los padres cada mañana sobre por qué su forma de educar es demasiado blanda.",
        score: 3,
        isRedFlag: false,
      },
      {
        id: "eth_02_d",
        text: "I do whatever requires the least amount of effort regardless of what the parents prefer.",
        textEs: "Hago lo que me implique el menor esfuerzo posible sin importar lo que prefieran los padres.",
        score: 1,
        isRedFlag: false,
      },
    ],
    idealAnswerExplanation: "A professional nanny functions as an extension of the parents' core values. Subverting their parenting style in secret destroys the foundation of care.",
    idealAnswerExplanationEs: "Una niñera profesional actúa como una extensión armónica de los padres. Socavar su estilo educativo a sus espaldas destruye la confianza y la seguridad del niño.",
    psychologicalInsight: "Integrity, humility, and willingness to collaborate with employers.",
    psychologicalInsightEs: "Integridad ética, humildad y lealtad laboral con los empleadores.",
    followUpInterviewQuestion: "How do you handle situations where a parent asks you to handle something differently than you are used to?",
    followUpInterviewQuestionEs: "¿Cómo manejas situaciones en las que un padre te pide abordar algo de forma distinta a como tú estás acostumbrada?",
  },

  // =========================================================================
  // SECTION 5: SITUATIONAL JUDGMENT SCENARIOS (REALISTIC DILEMMAS)
  // =========================================================================
  {
    id: "sit_01_allergic_reaction",
    category: "situational_judgment",
    categoryTitle: "Situational Judgment & Critical Thinking",
    categoryTitleEs: "Juicio Situacional y Pensamiento Crítico",
    question: "You are at a community playgroup with the 3-year-old. Another parent offers the children a snack with almond flour. Within 4 minutes, you notice the child rubbing their eyes, coughing, and developing red hives on their neck and lips. What is your exact sequence of actions?",
    questionEs: "Estás en un grupo de juego con el niño de 3 años. Otra mamá reparte galletas con harina de almendra. A los 4 minutos notas que el niño se frota los ojos, tose y le salen ronchas rojas en el cuello y labios. ¿Cuál es tu secuencia exacta de acción?",
    context: "Anaphylaxis protocol and urgent decision making under time pressure.",
    contextEs: "Protocolo de anafilaxia y toma rápida de decisiones bajo presión.",
    type: "single_choice",
    options: [
      {
        id: "sit_01_a",
        text: "1) Immediately administer EpiPen (if prescribed) / call emergency 911 right away. 2) Keep child upright/comfortable. 3) Call parents immediately after dispatching paramedics. 4) Stay with child every second.",
        textEs: "1) Administrar EpiPen de inmediato (si está recetado) / llamar a emergencias (911). 2) Mantener al niño erguido y cómodo. 3) Llamar a los padres inmediatamente después de pedir la ambulancia. 4) Permanecer pegada a él cada segundo.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "sit_01_b",
        text: "Pack up the stroller and drive the child in my own car to the nearest urgent care clinic to save money on ambulance fees.",
        textEs: "Subir al niño a mi propio auto y manejar a la clínica más cercana para ahorrarles el costo de la ambulancia.",
        score: 3,
        isRedFlag: true,
        redFlagReason: "Dangerous delay; an allergic airway obstruction can close in transit while driving unassisted.",
        redFlagReasonEs: "Demora peligrosa; una vía respiratoria con anafilaxia puede cerrarse por completo mientras manejas sola sin poder asistirlo.",
      },
      {
        id: "sit_01_c",
        text: "Call the parents repeatedly until they answer their phone before taking any medical action.",
        textEs: "Llamar insistentemente a los padres hasta que contesten el teléfono antes de llamar a emergencias.",
        score: 2,
        isRedFlag: true,
        redFlagReason: "Delaying life-saving emergency medical services while seeking parental permission.",
        redFlagReasonEs: "Retrasar atención médica vital en una emergencia aguda esperando contestación telefónica.",
      },
      {
        id: "sit_01_d",
        text: "Give the child a glass of water and wait 30 minutes to see if the hives go away on their own.",
        textEs: "Darle un vaso de agua y esperar 30 minutos a ver si las ronchas desaparecen solas.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Catastrophic negligence in the face of acute pediatric anaphylaxis signs.",
        redFlagReasonEs: "Negligencia catastrófica ante signos evidentes de anafilaxia pediátrica aguda.",
      },
    ],
    idealAnswerExplanation: "Airway swelling and hives indicate anaphylaxis. Paramedics/911 must be dispatched immediately without hesitation. Waiting or driving personally can be fatal.",
    idealAnswerExplanationEs: "La inflamación bucal y ronchas tras ingerir frutos secos señalan anafilaxia. El 911 debe llamarse sin dudar. Esperar o conducir sola puede costar la vida del menor.",
    psychologicalInsight: "Decisiveness under life-threatening pressure.",
    psychologicalInsightEs: "Capacidad de resolución y templanza en situaciones de emergencia vital.",
    followUpInterviewQuestion: "Are you comfortable using an auto-injector (EpiPen) and recognizing early allergic reactions?",
    followUpInterviewQuestionEs: "¿Te sientes cómoda reconociendo alergias tempranas y utilizando un autoinyector (EpiPen) si el pediatra lo prescribe?",
  },
  {
    id: "sit_02_playground_stranger",
    category: "situational_judgment",
    categoryTitle: "Situational Judgment & Critical Thinking",
    categoryTitleEs: "Juicio Situacional y Pensamiento Crítico",
    question: "You are at the playground. An unfamiliar adult approaches the bench, offers the 3-year-old a lollipop, and starts asking friendly questions like 'What is his name? Where do you live? Are you his mom?'. How do you handle this?",
    questionEs: "Estás en el parque de juegos. Un adulto desconocido se acerca al banco, le ofrece una paleta al niño de 3 años y te hace preguntas amables: '¿Cómo se llama el niño? ¿Dónde viven? ¿Eres su mamá?'. ¿Cómo actúas?",
    context: "Stranger vigilance, boundary setting, and child protection.",
    contextEs: "Alerta ante desconocidos, límites protectores y resguardo del menor.",
    type: "single_choice",
    options: [
      {
        id: "sit_02_a",
        text: "Step between the stranger and the child immediately: 'No thank you, he doesn't take food from strangers.' Do not disclose personal information, calmly gather our belongings, and move to a well-populated area or head home.",
        textEs: "Interponerme con firmeza entre la persona y el niño: 'No, gracias, no recibe comida de extraños'. No divulgar ningún dato privado, recoger nuestras cosas con calma y trasladarnos a una zona concurrida o volver a casa.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "sit_02_b",
        text: "Politely accept the lollipop and chat with the stranger because you don't want to seem rude or antisocial in public.",
        textEs: "Aceptar amablemente el dulce y conversar con la persona para no parecer grosera ni descortés en público.",
        score: 1,
        isRedFlag: true,
        redFlagReason: "People-pleasing behavior overrides basic protective instincts and safety boundaries.",
        redFlagReasonEs: "La complacencia social anula el instinto protector y los límites de resguardo del niño.",
      },
      {
        id: "sit_02_c",
        text: "Scream hysterically and start a physical fight with the person on the playground.",
        textEs: "Empezar a gritar histéricamente e iniciar una pelea física en el parque de juegos.",
        score: 2,
        isRedFlag: false,
      },
      {
        id: "sit_02_d",
        text: "Tell the stranger our neighborhood and schedule so they can come play with us again tomorrow.",
        textEs: "Decirle a la persona en qué colonia vivimos y a qué hora solemos venir para que vuelva a jugar con nosotros mañana.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Critical security violation: Disclosing personal household details to unknown strangers.",
        redFlagReasonEs: "Violación crítica de seguridad: Divulgar rutinas y domicilios familiares a desconocidos.",
      },
    ],
    idealAnswerExplanation: "Assertive, polite protective boundaries must be maintained. Caregivers should never disclose private names, addresses, or schedules to strangers.",
    idealAnswerExplanationEs: "Deben sostenerse límites asertivos de protección. Quien cuida a un niño nunca debe revelar nombres, horarios ni direcciones familiares a personas desconocidas.",
    psychologicalInsight: "Protective instincts vs. excessive social deference.",
    psychologicalInsightEs: "Instinto protector e inviolabilidad de fronteras frente a la sumisión social.",
    followUpInterviewQuestion: "How do you navigate interactions with other adults at parks while keeping 100% focus on the child's safety?",
    followUpInterviewQuestionEs: "¿Cómo manejas las interacciones con otros adultos en espacios públicos manteniendo tu atención al 100% en la seguridad del niño?",
  },

  // =========================================================================
  // SECTION 6: SIBLING & MULTI-CHILD DYNAMICS (WHEN FAMILY HAS >1 CHILD)
  // =========================================================================
  {
    id: "multi_01_bath_divided",
    category: "sibling_and_multichild",
    categoryTitle: "Multi-Child Supervision & Sibling Dynamics",
    categoryTitleEs: "Supervisión de Múltiples Niños y Dinámica entre Hermanos",
    question: "You are caring for two children: a 3-year-old and an 8-month-old baby. The baby is in 3 inches of bath water, and you hear a loud crash and crying from the 3-year-old in the living room. What is your exact action?",
    questionEs: "Cuidas a dos niños: uno de 3 años y un bebé de 8 meses. El bebé está en la tina con 8 cm de agua y escuchas un golpe fuerte y llanto del niño de 3 años en la sala. ¿Cuál es tu acción exacta?",
    context: "Divided attention and touch supervision across multiple young children.",
    contextEs: "Atención dividida y supervisión continua al tacto en familias con varios niños.",
    type: "single_choice",
    options: [
      {
        id: "multi_01_a",
        text: "Never leave the baby in water even for a split second. Immediately scoop the baby up in a towel in my arms and walk together to inspect and comfort the 3-year-old.",
        textEs: "Jamás dejar al bebé en el agua ni por una fracción de segundo. Lo saco de inmediato envuelto en una toalla en mis brazos y vamos juntos a revisar y consolar al niño de 3 años.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "multi_01_b",
        text: "Run out of the bathroom for just 10 seconds to see if the 3-year-old is bleeding, then sprint back to the baby.",
        textEs: "Correr fuera del baño solo 10 segundos a ver si el de 3 años está sangrando y regresar corriendo a la tina.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Critical multi-child safety hazard: Leaving an infant unattended in bath water while checking another child leads to drowning.",
        redFlagReasonEs: "Peligro mortal crítico en familias con varios niños: Dejar a un bebé en el agua para revisar a otro causa ahogamiento inmediato.",
      },
      {
        id: "multi_01_c",
        text: "Yell as loud as I can from the bathroom: 'Are you okay?! Stop crying, I will be out in 5 minutes!'",
        textEs: "Gritar lo más fuerte que pueda desde el baño: '¡¿Estás bien?! ¡Deja de llorar, salgo en 5 minutos!'",
        score: 3,
        isRedFlag: false,
      },
      {
        id: "multi_01_d",
        text: "Drain the bathwater with baby still inside and tell baby to hold onto the tub while I check the living room.",
        textEs: "Quitar el tapón de la tina dejando al bebé adentro y decirle que se agarre fuerte mientras voy a la sala.",
        score: 1,
        isRedFlag: true,
        redFlagReason: "Infants can slip, hit their head, and drown even in shallow draining water.",
        redFlagReasonEs: "Los bebés pueden resbalar y golpearse la cabeza en la tina vaciándose.",
      },
    ],
    idealAnswerExplanation: "The golden rule of multi-child childcare: Water supervision always takes precedence. If the other child needs help, the baby leaves the water in your arms immediately.",
    idealAnswerExplanationEs: "La regla de oro al cuidar varios niños: La supervisión en agua siempre tiene prioridad absoluta. Si el otro niño necesita atención, el bebé sale del agua en brazos de inmediato.",
    psychologicalInsight: "Vigilance under crisis without abandoning basic pediatric safety protocols.",
    psychologicalInsightEs: "Vigilancia en situaciones de crisis simultáneas sin sacrificar protocolos pediátricos básicos.",
    followUpInterviewQuestion: "How do you manage bath time and bedtime routines smoothly when caring for siblings of different ages?",
    followUpInterviewQuestionEs: "¿Cómo organizas la hora del baño y la rutina de dormir cuando cuidas a hermanos de distintas edades?",
  },
  {
    id: "multi_02_choking_hazard_toys",
    category: "sibling_and_multichild",
    categoryTitle: "Multi-Child Supervision & Sibling Dynamics",
    categoryTitleEs: "Supervisión de Múltiples Niños y Dinámica entre Hermanos",
    question: "The 3-year-old loves playing with small Lego bricks and marbles. Their 1-year-old sibling crawls on the floor putting everything in their mouth. How do you permanently manage this without shutting down the 3-year-old's play?",
    questionEs: "Al niño de 3 años le fascina armar Legos pequeños y canicas. Su hermanito de 1 año gatea por el suelo llevándose todo a la boca. ¿Cómo organizas esto de forma permanente sin apagar el juego del de 3 años?",
    context: "Choking hazard segregation between older toddlers and crawling babies.",
    contextEs: "Segregación de piezas de asfixia entre niños mayores y bebés que gatean.",
    type: "single_choice",
    options: [
      {
        id: "multi_02_a",
        text: "Establish clear physical zones: 3yo plays with small parts on a high table or designated enclosed zone; teach the 3yo 'baby-safe zones'; perform floor sweeps; and provide the 1yo with age-appropriate chunky sensory toys.",
        textEs: "Definir zonas físicas claras: el de 3 años juega con piezas chicas en una mesa alta o área delimitada; enseñarle la 'zona segura para el bebé'; revisar el suelo constantemente y darle al de 1 año juguetes grandes y sensoriales.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "multi_02_b",
        text: "Ban the 3-year-old from having any small toys in the house until the baby turns 4 years old.",
        textEs: "Prohibirle al niño de 3 años tener juguetes pequeños en la casa hasta que el hermanito cumpla 4 años.",
        score: 4,
        isRedFlag: false,
      },
      {
        id: "multi_02_c",
        text: "Let them play together on the floor with the Legos and just say 'No, baby, don't eat that' whenever the baby grabs one.",
        textEs: "Dejar que jueguen juntos en el suelo con los Legos y solo decirle 'No, bebé, eso no se come' cada vez que agarre una pieza.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Critical choking risk: Verbal reminders to a 1-year-old cannot prevent rapid airway obstruction.",
        redFlagReasonEs: "Riesgo crítico de asfixia: Los recordatorios verbales a un bebé de 1 año no evitan que se atragante en segundos.",
      },
      {
        id: "multi_02_d",
        text: "Put the baby in a crib in another room all afternoon so the 3-year-old can play freely.",
        textEs: "Dejar al bebé en la cuna en otro cuarto toda la tarde para que el de 3 años juegue a sus anchas.",
        score: 2,
        isRedFlag: false,
      },
    ],
    idealAnswerExplanation: "Older toddlers need developmentally rich fine-motor toys, but babies are oral explorers. Environmental zoning (tables, baby gates) and older-child empathy training are essential.",
    idealAnswerExplanationEs: "El niño de 3 años necesita motricidad fina, pero el bebé explora con la boca. La zonificación del espacio y enseñar al mayor a cuidar a su hermano es la mejor práctica.",
    psychologicalInsight: "Environmental engineering and proactive hazard segregation.",
    psychologicalInsightEs: "Capacidad de diseño del entorno y prevención proactiva de riesgos cruzados.",
    followUpInterviewQuestion: "Can you give an example of how you foster cooperation and sharing between siblings with an age gap?",
    followUpInterviewQuestionEs: "¿Puedes darme un ejemplo de cómo fomentas la cooperación y convivencia entre hermanos con diferencia de edad?",
  },
  {
    id: "multi_03_sibling_conflict",
    category: "sibling_and_multichild",
    categoryTitle: "Multi-Child Supervision & Sibling Dynamics",
    categoryTitleEs: "Supervisión de Múltiples Niños y Dinámica entre Hermanos",
    question: "The younger sibling grabs a toy train from the 3-year-old. The 3-year-old forcefully shoves the baby onto the rug, and both start screaming. What is your exact conflict response?",
    questionEs: "El hermanito menor le arrebata un tren de juguete al niño de 3 años. El de 3 años empuja con fuerza al bebé contra la alfombra y ambos se ponen a gritar. ¿Cuál es tu respuesta exacta al conflicto?",
    context: "Sibling physical aggression, emotional co-regulation, and boundary enforcement.",
    contextEs: "Agresión física entre hermanos, co-regulación emocional y límites firmes y respetuosos.",
    type: "single_choice",
    options: [
      {
        id: "multi_03_a",
        text: "1) Check baby for injury and comfort them. 2) Position myself as a calm physical buffer. 3) Validate 3yo's anger: 'You were so mad he grabbed your train!' 4) Hold firm boundary: 'I will not let you push. Pushing hurts. Next time say: I am using this.'",
        textEs: "1) Revisar que el bebé no tenga golpes y consolarlo. 2) Ponerme con serenidad como barrera física protectora. 3) Validar el enojo del de 3 años: '¡Te enojó mucho que te quitara el tren!'. 4) Sostener el límite firme: 'No te permitiré empujar. Empujar duele. La próxima vez dile: Lo estoy usando'.",
        score: 10,
        isRedFlag: false,
      },
      {
        id: "multi_03_b",
        text: "Immediately scream at the 3-year-old: 'You are older, you should know better! Give all your toys to your sibling right now!'",
        textEs: "Gritarle inmediatamente al de 3 años: '¡Tú eres el mayor, deberías saberlo! ¡Entrégale todos tus juguetes a tu hermanito ya mismo!'",
        score: 2,
        isRedFlag: false,
      },
      {
        id: "multi_03_c",
        text: "Give the 3-year-old a hard push back so they know how their sibling felt on the floor.",
        textEs: "Darle un empujón fuerte de vuelta al de 3 años para que aprenda lo que sintió su hermano en el suelo.",
        score: 0,
        isRedFlag: true,
        redFlagReason: "Physical retaliation against a child by a caregiver.",
        redFlagReasonEs: "Represalia física violenta contra un niño por parte de la cuidadora.",
      },
      {
        id: "multi_03_d",
        text: "Ignore both of them and let them fight it out so they build character and street smarts.",
        textEs: "Ignorar a ambos y dejar que se peleen solos para que aprendan a defenderse en la vida.",
        score: 1,
        isRedFlag: true,
        redFlagReason: "Neglect of infant safety during physical peer/sibling altercations.",
        redFlagReasonEs: "Desatención peligrosa de la integridad física de un bebé ante agresiones.",
      },
    ],
    idealAnswerExplanation: "Caregivers must protect the physical safety of the younger child without villifying the older child. Validating the 3-year-old's emotion while holding a firm boundary against violence builds sibling empathy.",
    idealAnswerExplanationEs: "Se debe proteger la integridad del menor sin satanizar al mayor. Validar la emoción del niño de 3 años mientras se prohíbe tajantemente la violencia fomenta la empatía fraterna.",
    psychologicalInsight: "Equanimity, physical de-escalation, and non-punitive boundary holding.",
    psychologicalInsightEs: "Ecuanimidad, desescalamiento no violento y enseñanza de límites entre hermanos.",
    followUpInterviewQuestion: "How do you handle sibling rivalry and jealousy when one child requires more immediate attention?",
    followUpInterviewQuestionEs: "¿Cómo manejas los celos y la rivalidad entre hermanos cuando uno de ellos demanda atención inmediata?",
  },
];
