import { QuestionBankGroup, QuestionBankItem } from "./types";

export const DEFAULT_QUESTION_BANK_GROUPS: QuestionBankGroup[] = [
  {
    id: "grp_safety",
    nameEs: "🛡️ Seguridad, Emergencias y Salud",
    nameEn: "🛡️ Safety, First Aid & Health",
    descriptionEs: "Verificación de carnet de vacunas, protocolos ante fiebre súbita y disposición para RCP infantil.",
    descriptionEn: "Vaccination status, emergency protocols for sudden high fever, and CPR willingness.",
    icon: "ShieldCheck",
    questions: [
      {
        id: "qbank_safe_01",
        groupId: "grp_safety",
        groupNameEs: "Seguridad y Salud",
        groupNameEn: "Safety & Health",
        type: "multiple_choice",
        prompt: "Vaccination status: Do you have an up-to-date vaccine record (Tetanus, Pertussis/Tdap, Flu)?",
        promptEs: "Estado de vacunación: ¿Cuenta con carnet de vacunas al día (Tétanos, Tos Ferina/Tdap, Influenza)?",
        options: [
          "Yes, up to date with official card",
          "Partially up to date, willing to update immediately",
          "I prefer not to receive vaccines",
        ],
        optionsEs: [
          "Sí, carnet completo al día con constancia médica",
          "Parcialmente al día, dispuesta a actualizarlo de inmediato",
          "No tengo vacunas completas / No dispuesta",
        ],
        required: true,
      },
      {
        id: "qbank_safe_02",
        groupId: "grp_safety",
        groupNameEs: "Seguridad y Salud",
        groupNameEn: "Safety & Health",
        type: "multiple_choice",
        prompt: "Pediatric First Aid: Would you be willing to attend an infant CPR and choking certification course sponsored by the family?",
        promptEs: "Primeros Auxilios: ¿Estaría dispuesta a realizar un curso de reanimación cardiopulmonar (RCP) infantil si la familia lo financia?",
        options: [
          "Yes, absolutely willing and enthusiastic",
          "I already have a valid active CPR certificate",
          "No, not interested in additional training",
        ],
        optionsEs: [
          "Sí, totalmente dispuesta y entusiasmada",
          "Ya poseo certificado vigente activo de la Cruz Roja / entidad médica",
          "No, no me interesa realizar cursos adicionales",
        ],
        required: true,
      },
      {
        id: "qbank_safe_03",
        groupId: "grp_safety",
        groupNameEs: "Seguridad y Salud",
        groupNameEn: "Safety & Health",
        type: "open_text",
        prompt: "Describe step by step what you would do if the child develops a sudden fever of 39°C (102.2°F) or shows signs of dehydration while alone with you.",
        promptEs: "Describe paso a paso cómo actuarías si el niño presenta fiebre súbita de 39°C o muestra signos de malestar agudo mientras estás a solas con él.",
        required: true,
      },
    ],
  },
  {
    id: "grp_tech_privacy",
    nameEs: "📱 Tecnología, Pantallas y Privacidad",
    nameEn: "📱 Tech, Screen Time & Privacy",
    descriptionEs: "Límites estrictos sobre el uso de celular durante la jornada y confidencialidad en redes sociales.",
    descriptionEn: "Strict smartphone usage policies and social media confidentiality for family privacy.",
    icon: "Smartphone",
    questions: [
      {
        id: "qbank_tech_01",
        groupId: "grp_tech_privacy",
        groupNameEs: "Tecnología y Privacidad",
        groupNameEn: "Tech & Privacy",
        type: "multiple_choice",
        prompt: "Personal phone policy: Are you comfortable keeping your phone in silent/focus mode during active childcare hours?",
        promptEs: "Política de celular: ¿Aceptas mantener el teléfono en silencio/modo no molestar durante horas activas de cuidado (solo revisándolo en descansos o emergencias)?",
        options: [
          "Agree completely; total focus on the child",
          "Only for urgent family calls from my own relatives",
          "I need continuous access to my smartphone",
        ],
        optionsEs: [
          "Acepto totalmente; el niño requiere atención 100% enfocada",
          "Solo para llamadas urgentes de mi familia o de los padres",
          "Necesito consultar mi teléfono con frecuencia durante el día",
        ],
        required: true,
      },
      {
        id: "qbank_tech_02",
        groupId: "grp_tech_privacy",
        groupNameEs: "Tecnología y Privacidad",
        groupNameEn: "Tech & Privacy",
        type: "multiple_choice",
        prompt: "Social Media & Photos: Do you accept our strict policy of never posting photos or videos of our child or our home on Instagram, TikTok, or WhatsApp status?",
        promptEs: "Redes Sociales: ¿Aceptas la norma estricta de no subir fotos ni videos del niño ni del hogar a Instagram, WhatsApp o TikTok?",
        options: [
          "100% agreement. Strict confidentiality is professional standard.",
          "I would only share with close family if permitted.",
          "I usually post my workday moments.",
        ],
        optionsEs: [
          "Acepto al 100%. La privacidad y seguridad del menor es innegociable.",
          "Solo enviaría fotos a los padres por mensaje privado.",
          "Prefiero poder compartir fotos de mi día a día.",
        ],
        required: true,
      },
    ],
  },
  {
    id: "grp_nutrition",
    nameEs: "🍎 Alimentación, Alergias y Rutinas",
    nameEn: "🍎 Nutrition, Allergies & Routines",
    descriptionEs: "Experiencia en Baby-Led Weaning (BLW), prevención de alergias y manejo de selectividad alimentaria.",
    descriptionEn: "BLW feeding techniques, allergy management, and coping with picky eaters.",
    icon: "Utensils",
    questions: [
      {
        id: "qbank_nutr_01",
        groupId: "grp_nutrition",
        groupNameEs: "Alimentación",
        groupNameEn: "Nutrition",
        type: "multiple_choice",
        prompt: "Food preparation: What is your level of experience preparing baby purees or finger foods (BLW)?",
        promptEs: "Preparación de alimentos: ¿Cuál es tu experiencia preparando comidas para niños pequeños o cortes seguros (BLW)?",
        options: [
          "Extensive experience cutting finger foods safely & making healthy meals",
          "Basic cooking experience; follow recipes easily",
          "I prefer parents provide all meals prepared in advance",
        ],
        optionsEs: [
          "Amplia experiencia en cortes seguros para evitar atragantamiento y comida balanceada",
          "Conocimiento básico de cocina; sigo instrucciones sencillas",
          "Prefiero que los padres dejen todas las comidas preparadas de antemano",
        ],
        required: true,
      },
      {
        id: "qbank_nutr_02",
        groupId: "grp_nutrition",
        groupNameEs: "Alimentación",
        groupNameEn: "Nutrition",
        type: "open_text",
        prompt: "If the child refuses to eat or repeatedly throws their plate on the floor, what is your constructive reaction?",
        promptEs: "Si el niño se niega rotundamente a comer o tira el plato al suelo repetidamente, ¿cómo respondes para no crear conflicto ni premiar la conducta?",
        required: true,
      },
    ],
  },
  {
    id: "grp_discipline",
    nameEs: "🧸 Crianza Respetuosa y Manejo de Rabietas",
    nameEn: "🧸 Positive Discipline & Tantrums",
    descriptionEs: "Estrategias de co-regulación emocional, validación y alternativas sin gritos ni castigos físicos.",
    descriptionEn: "Co-regulation techniques, emotional validation, and non-punitive gentle boundaries.",
    icon: "HeartHandshake",
    questions: [
      {
        id: "qbank_disc_01",
        groupId: "grp_discipline",
        groupNameEs: "Crianza y Emociones",
        groupNameEn: "Parenting & Emotions",
        type: "open_text",
        prompt: "Our family follows respectful parenting (no yelling, no physical discipline). How do you handle intense public or bedtime tantrums?",
        promptEs: "En nuestra familia no permitimos gritos ni castigos físicos. ¿Qué técnicas de acompañamiento emocional utilizas ante un berrinche o pataleta fuerte?",
        required: true,
      },
      {
        id: "qbank_disc_02",
        groupId: "grp_discipline",
        groupNameEs: "Crianza y Emociones",
        groupNameEn: "Parenting & Emotions",
        type: "multiple_choice",
        prompt: "Discipline approach: What is your perspective on 'time-out' (isolation) vs 'time-in' (sitting together to calm down)?",
        promptEs: "Enfoque de límites: ¿Qué opinas del 'tiempo fuera' (aislar al niño en un rincón) vs 'tiempo dentro' (acompañarlo sentado hasta recuperar la calma)?",
        options: [
          "I strongly support time-in (co-regulation and comfort until calm)",
          "I use whatever method the parents request",
          "I believe isolated time-outs are the only effective consequence",
        ],
        optionsEs: [
          "Prefiero tiempo dentro (acompañar, validar emoción y enseñar a calmarse)",
          "Me adapto 100% a la filosofía que los padres me indiquen",
          "Considero que aislar al niño en un rincón es la única forma que entienda",
        ],
        required: true,
      },
    ],
  },
  {
    id: "grp_logistics",
    nameEs: "🚗 Movilidad, Licencia y Disponibilidad",
    nameEn: "🚗 Mobility, Driving & Availability",
    descriptionEs: "Licencia de conducir con récord limpio, vehículo propio y flexibilidad para viajar o eventos familiares.",
    descriptionEn: "Driver's license, clean driving record, and flexibility for travel or overtime.",
    icon: "Car",
    questions: [
      {
        id: "qbank_log_01",
        groupId: "grp_logistics",
        groupNameEs: "Movilidad y Logística",
        groupNameEn: "Mobility & Logistics",
        type: "multiple_choice",
        prompt: "Driving: Do you have a valid driver's license with a clean driving record?",
        promptEs: "Conducción: ¿Posee licencia de conducir vigente y récord de manejo sin infracciones graves?",
        options: [
          "Yes, clean record with my own safe vehicle",
          "Yes, clean record; comfortable driving family car",
          "I do not drive / no license",
        ],
        optionsEs: [
          "Sí, récord limpio y vehículo propio en óptimas condiciones",
          "Sí, récord limpio y dispuesta a conducir el auto de la familia con sillas infantiles",
          "No conduzco / No poseo licencia de manejo",
        ],
        required: false,
      },
      {
        id: "qbank_log_02",
        groupId: "grp_logistics",
        groupNameEs: "Movilidad y Logística",
        groupNameEn: "Mobility & Logistics",
        type: "multiple_choice",
        prompt: "Overtime & Travel: Would you be available to travel with the family on vacations or stay occasional weekend evenings with advance notice?",
        promptEs: "Disponibilidad: ¿Estaría disponible para viajar con la familia en vacaciones o cubrir horas extras con previo aviso remunerado?",
        options: [
          "Yes, full flexibility with prior agreement",
          "Occasional evenings only, no long travel",
          "Strict fixed hours only",
        ],
        optionsEs: [
          "Sí, total disponibilidad para viajar o turnos especiales con previo aviso",
          "Solo horas extras en la misma ciudad ocasionalmente",
          "Horario estrictamente fijo sin posibilidad de variación",
        ],
        required: false,
      },
    ],
  },
  // =========================================================================
  // GRUPO 6: ADULTOS MAYORES - MOVILIDAD Y PREVENCIÓN DE CAÍDAS
  // =========================================================================
  {
    id: "grp_elderly_mobility",
    nameEs: "👵 Adulto Mayor: Movilidad y Prevención de Caídas",
    nameEn: "👵 Elderly: Mobility & Fall Prevention",
    descriptionEs: "Técnicas de transferencia segura cama-silla, uso de andador y protocolo de emergencia ante caídas.",
    descriptionEn: "Safe transfer techniques, walker/wheelchair handling, and fall emergency protocol.",
    icon: "Activity",
    careCategory: "elderly_care",
    questions: [
      {
        id: "qbank_eld_mob_01",
        groupId: "grp_elderly_mobility",
        groupNameEs: "Movilidad en Adulto Mayor",
        groupNameEn: "Elderly Mobility",
        type: "multiple_choice",
        careCategory: "elderly_care",
        prompt: "Fall Protocol: If an elderly person slips and falls to the ground while alone with you, what is your immediate first step?",
        promptEs: "Protocolo de Caídas: Si el adulto mayor resbala y cae al suelo mientras está contigo, ¿cuál es tu primera acción?",
        options: [
          "Do not lift them immediately; check consciousness, breathing, pain, and signs of fracture before moving",
          "Immediately pull them up by their arms to get them back into a chair as fast as possible",
          "Leave them lying on the floor and go outside to find a neighbor",
        ],
        optionsEs: [
          "No levantarlo bruscamente; evaluar consciencia, dolor agudo, cadera y cabeza antes de cualquier movimiento",
          "Jalarlo inmediatamente de los brazos para subirlo a la silla lo antes posible",
          "Dejarlo en el piso e ir a buscar vecinos a la calle",
        ],
        required: true,
      },
      {
        id: "qbank_eld_mob_02",
        groupId: "grp_elderly_mobility",
        groupNameEs: "Movilidad en Adulto Mayor",
        groupNameEn: "Elderly Mobility",
        type: "open_text",
        careCategory: "elderly_care",
        prompt: "Describe your experience and technique for assisting an elderly person with reduced mobility in moving between bed, wheelchair, and bathroom safely.",
        promptEs: "Describe tu experiencia y técnica postural para transferir a un adulto mayor con movilidad reducida entre la cama, la silla de ruedas y el baño sin riesgo de lesiones.",
        required: true,
      },
    ],
  },
  // =========================================================================
  // GRUPO 7: ADULTOS MAYORES - MEDICACIÓN Y CONTROL DE SALUD
  // =========================================================================
  {
    id: "grp_elderly_medication",
    nameEs: "💊 Adulto Mayor: Medicación y Signos Vitales",
    nameEn: "💊 Elderly: Medication & Vital Signs",
    descriptionEs: "Administración estricta de pastilleros, registro de presión/glucosa y respuesta ante omisiones.",
    descriptionEn: "Strict medication pillbox adherence, BP/glucose tracking, and handling refusal or confusion.",
    icon: "Pill",
    careCategory: "elderly_care",
    questions: [
      {
        id: "qbank_eld_med_01",
        groupId: "grp_elderly_medication",
        groupNameEs: "Medicación y Salud",
        groupNameEn: "Medication & Health",
        type: "multiple_choice",
        careCategory: "elderly_care",
        prompt: "Vital Signs: Are you experienced in measuring and logging blood pressure, blood glucose, and oxygen saturation?",
        promptEs: "Signos Vitales: ¿Tiene experiencia tomando y registrando la tensión arterial (tensiómetro), glucosa capilar y saturación de oxígeno?",
        options: [
          "Yes, experienced and comfortable keeping daily clinical logs",
          "Basic familiarity with digital monitors, willing to be trained",
          "No experience with medical equipment",
        ],
        optionsEs: [
          "Sí, amplia experiencia y mantengo bitácora diaria de control",
          "Familiaridad básica con aparatos digitales, dispuesta a ser guiada",
          "Sin experiencia en toma de signos vitales",
        ],
        required: true,
      },
      {
        id: "qbank_eld_med_02",
        groupId: "grp_elderly_medication",
        groupNameEs: "Medicación y Salud",
        groupNameEn: "Medication & Health",
        type: "multiple_choice",
        careCategory: "elderly_care",
        prompt: "Medication Refusal: What would you do if the elderly person refuses to take their prescribed heart medication?",
        promptEs: "Negativa de Medicación: ¿Qué haces si el adulto mayor se niega rotundamente a tomar su medicamento para el corazón o la presión?",
        options: [
          "Stay patient, never force them; wait a few minutes, explain gently, and inform the family/doctor if refusal persists",
          "Crush the pill secretly in their juice without telling anyone",
          "Argue and scold them until they swallow it out of fear",
        ],
        optionsEs: [
          "Tener paciencia y nunca forzar; esperar unos minutos, explicar suavemente y notificar a la familia/médico si persiste la negativa",
          "Moler la pastilla a escondidas en la comida sin consultar al médico",
          "Regañar y discutir con firmeza hasta que la trague",
        ],
        required: true,
      },
    ],
  },
  // =========================================================================
  // GRUPO 8: ADULTOS MAYORES - DETERIORO COGNITIVO Y ALZHEIMER
  // =========================================================================
  {
    id: "grp_elderly_cognitive",
    nameEs: "🧠 Adulto Mayor: Deterioro Cognitivo y Alzheimer",
    nameEn: "🧠 Elderly: Cognitive Decline & Dementia",
    descriptionEs: "Manejo empático de desorientación, síndrome de atardecer (sundowning) y validación emocional.",
    descriptionEn: "Empathetic dementia validation, evening restlessness (sundowning), and extreme patience.",
    icon: "Brain",
    careCategory: "elderly_care",
    questions: [
      {
        id: "qbank_eld_cog_01",
        groupId: "grp_elderly_cognitive",
        groupNameEs: "Cognición y Memoria",
        groupNameEn: "Cognition & Memory",
        type: "multiple_choice",
        careCategory: "elderly_care",
        prompt: "Disorientation Episode: If an elderly person with dementia insists they need to 'leave for work' or ask for deceased parents, how do you respond?",
        promptEs: "Episodio de Desorientación: Si el adulto mayor con demencia insiste en que 'debe irse al trabajo' o pregunta por sus padres ya fallecidos, ¿cómo respondes?",
        options: [
          "Validate their emotion with empathy and gentle redirection (Validation Therapy), avoiding harsh arguments",
          "Confront them repeatedly telling them their parents died decades ago",
          "Lock the doors and leave them alone in their room",
        ],
        optionsEs: [
          "Validar su emoción con calidez y redirigir con suavidad (Terapia de Validación), sin confrontar bruscamente",
          "Discutirle repetidamente recordándole que sus padres fallecieron hace décadas",
          "Encerrarlo en su habitación para que no insista",
        ],
        required: true,
      },
      {
        id: "qbank_eld_cog_02",
        groupId: "grp_elderly_cognitive",
        groupNameEs: "Cognición y Memoria",
        groupNameEn: "Cognition & Memory",
        type: "open_text",
        careCategory: "elderly_care",
        prompt: "What daily cognitive stimulation, music, or conversation activities do you enjoy implementing with seniors to maintain their mental vitality?",
        promptEs: "¿Qué actividades de estimulación cognitiva, música, juegos de mesa o recuerdos practicas para mantener la vitalidad y el buen ánimo del adulto mayor?",
        required: true,
      },
    ],
  },
  // =========================================================================
  // GRUPO 9: DISCAPACIDAD - REGULACIÓN Y CRISIS SENSORIALES
  // =========================================================================
  {
    id: "grp_disability_crisis",
    nameEs: "♿ Discapacidad: Regulación y Crisis Sensoriales",
    nameEn: "♿ Disability: Sensory Regulation & De-escalation",
    descriptionEs: "Acompañamiento en sobrecarga sensorial (TEA, neurodivergencia) y desescalada respetuosa.",
    descriptionEn: "Support during sensory overload (Autism/Neurodiversity) and respectful non-punitive de-escalation.",
    icon: "HeartHandshake",
    careCategory: "disability_care",
    questions: [
      {
        id: "qbank_dis_cri_01",
        groupId: "grp_disability_crisis",
        groupNameEs: "Regulación Sensorial",
        groupNameEn: "Sensory Regulation",
        type: "open_text",
        careCategory: "disability_care",
        prompt: "Sensory Meltdown: How do you identify early triggers of sensory overload in a neurodivergent person, and what is your calm de-escalation protocol?",
        promptEs: "Crisis Sensorial: ¿Cómo identificas las señales tempranas de sobrecarga sensorial en una persona neurodivergente y cuál es tu protocolo de contención sin coerción?",
        required: true,
      },
      {
        id: "qbank_dis_cri_02",
        groupId: "grp_disability_crisis",
        groupNameEs: "Regulación Sensorial",
        groupNameEn: "Sensory Regulation",
        type: "multiple_choice",
        careCategory: "disability_care",
        prompt: "De-escalation Approach: During an acute behavioral dysregulation episode, what is your top priority?",
        promptEs: "Prioridad en Crisis: Durante una crisis aguda de desregulación conductual, ¿cuál es tu máxima prioridad?",
        options: [
          "Ensure physical safety of the person and environment, reduce sensory noise, stay calm without overwhelming them",
          "Physically restrain them forcefully until they stop moving",
          "Raise my voice to establish authority immediately",
        ],
        optionsEs: [
          "Garantizar la seguridad física de la persona y el entorno, bajar luces/ruidos y mantener presencia tranquila sin abrumar",
          "Sujetarla con fuerza e inmovilizarla contra el suelo",
          "Gritarle con firmeza para imponer autoridad",
        ],
        required: true,
      },
    ],
  },
  // =========================================================================
  // GRUPO 10: DISCAPACIDAD - AUTONOMÍA Y APOYO TERAPÉUTICO
  // =========================================================================
  {
    id: "grp_disability_autonomy",
    nameEs: "🌟 Discapacidad: Autonomía y Rehabilitación",
    nameEn: "🌟 Disability: Autonomy & Therapy Support",
    descriptionEs: "Filosofía de capacitación en lugar de sobreprotección, seguimiento de terapias y comunicación adaptada.",
    descriptionEn: "Empowerment over overprotection, therapy exercise follow-through, and adapted communication.",
    icon: "Sparkles",
    careCategory: "disability_care",
    questions: [
      {
        id: "qbank_dis_aut_01",
        groupId: "grp_disability_autonomy",
        groupNameEs: "Autonomía y Terapia",
        groupNameEn: "Autonomy & Therapy",
        type: "multiple_choice",
        careCategory: "disability_care",
        prompt: "Empowerment vs Overprotection: When assisting someone with physical or intellectual disabilities, what is your approach to daily tasks?",
        promptEs: "Autonomía vs Sobreprotección: Al apoyar a alguien con discapacidad física o intelectual en tareas diarias (vestirse, comer), ¿cuál es tu enfoque?",
        options: [
          "Provide only the necessary support, allowing them time to do as much as possible independently",
          "Do everything for them quickly to save time, even if they could do parts of it",
          "Refuse to help so they are forced to struggle alone",
        ],
        optionsEs: [
          "Brindar solo el apoyo necesario, dando el tiempo que requiera para que haga por sí mismo todo lo que pueda",
          "Hacerle todo yo rápidamente para no perder tiempo, aunque él o ella pudiera intentarlo",
          "No ayudarle en nada para que aprenda a la fuerza",
        ],
        required: true,
      },
      {
        id: "qbank_dis_aut_02",
        groupId: "grp_disability_autonomy",
        groupNameEs: "Autonomía y Terapia",
        groupNameEn: "Autonomy & Therapy",
        type: "multiple_choice",
        careCategory: "disability_care",
        prompt: "Adapted Communication: Do you have experience or openness to using AAC (Augmentative and Alternative Communication) such as pictograms, communication boards, or tablet apps?",
        promptEs: "Comunicación Aumentativa: ¿Tiene experiencia o disposición para usar sistemas de comunicación adaptada (pictogramas, tableros visuales, lengua de señas o apps en tablet)?",
        options: [
          "Yes, experienced with AAC methods and very patient",
          "No prior experience, but fully willing and eager to learn the family's system",
          "I only work with people who speak verbally",
        ],
        optionsEs: [
          "Sí, cuento con experiencia en comunicación aumentativa/pictogramas y mucha paciencia",
          "Sin experiencia previa, pero con total disposición para aprender el sistema de la familia",
          "Solo atiendo a personas que se comuniquen verbalmente",
        ],
        required: true,
      },
    ],
  },
  // =========================================================================
  // GRUPO 11: DISCAPACIDAD - CUIDADOS POSTURALES Y SILLA DE RUEDAS
  // =========================================================================
  {
    id: "grp_disability_transfers",
    nameEs: "♿ Discapacidad: Sillas Adaptadas y Cuidados Posturales",
    nameEn: "♿ Disability: Wheelchair Handling & Postural Care",
    descriptionEs: "Manejo de silla de ruedas en vía pública, transferencias ergonómicas y prevención de úlceras por presión.",
    descriptionEn: "Wheelchair handling, ergonomic body mechanics, and pressure injury prevention.",
    icon: "ShieldCheck",
    careCategory: "disability_care",
    questions: [
      {
        id: "qbank_dis_trn_01",
        groupId: "grp_disability_transfers",
        groupNameEs: "Postura y Movilidad",
        groupNameEn: "Postural & Mobility",
        type: "open_text",
        careCategory: "disability_care",
        prompt: "Wheelchair & Community: What safety precautions do you take when navigating city streets, ramps, and curbs with an adapted wheelchair?",
        promptEs: "Manejo en Vía Pública: ¿Qué precauciones de seguridad tomas al transitar con una silla de ruedas por rampas, cordones y cruces peatonales?",
        required: true,
      },
      {
        id: "qbank_dis_trn_02",
        groupId: "grp_disability_transfers",
        groupNameEs: "Postura y Movilidad",
        groupNameEn: "Postural & Mobility",
        type: "multiple_choice",
        careCategory: "disability_care",
        prompt: "Pressure Sore Prevention: How often should an immobilized person's posture be rotated or shifted to prevent pressure sores (ulcers)?",
        promptEs: "Prevención de Escaras: ¿Cada cuánto tiempo se deben realizar cambios de postura o alivio de presión en una persona encamada o en silla de ruedas?",
        options: [
          "Every 2 hours while in bed, and weight shifts every 15-30 minutes in a wheelchair",
          "Only once per day before bedtime",
          "Changes of posture are not necessary unless the person asks",
        ],
        optionsEs: [
          "Cada 2 horas en cama y alivios de presión frecuentes cada 20-30 minutos en silla de ruedas",
          "Solo una vez al día antes de dormir",
          "No son necesarios los cambios posturales a menos que la persona lo pida",
        ],
        required: true,
      },
    ],
  },
];

