import { CareCategory, RecommendedProduct } from "./types";
export type { RecommendedProduct };

export const RECOMMENDED_PRODUCTS: RecommendedProduct[] = [
  // ==========================================
  // 1. CHILDCARE (Infantil)
  // ==========================================
  {
    id: "prod_montessori_busyboard",
    title: "Montessori Wooden Busy Board for Fine Motor Skills",
    titleEs: "Tablero Sensorial Montessori de Madera para Motricidad Fina",
    category: "activities",
    careCategory: "childcare",
    categoryLabelEs: "Actividades & Desarrollo",
    categoryLabelEn: "Activities & Skills",
    targetMinAge: 1,
    targetMaxAge: 4,
    ageBadge: "1 - 4 years",
    ageBadgeEs: "1 - 4 años",
    description: "Multi-activity sensory latch board with switches, latches, gears and clock to promote independent problem-solving.",
    descriptionEs: "Tablero de madera natural con cerrojos, engranajes, interruptores y cordones. Fomenta la concentración y calma la frustración.",
    pedagogicalBenefitEs: "Fomenta la autorregulación motriz y coordinación mano-ojo según el método Montessori.",
    pedagogicalBenefitEn: "Develops finger dexterity, logical thinking, and autonomous task focus.",
    imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=montessori+busy+board+toddlers&tag=matchcaring-20",
    priceEstimate: "$29.99",
    rating: 4.9,
    reviewCount: 1420,
    badge: "Parent Favorite",
    badgeEs: "Top Recomendado",
  },
  {
    id: "prod_calm_down_book",
    title: "The Color Monster / Pop-Up Book of Feelings",
    titleEs: "El Monstruo de Colores: Libro Pop-Up de Educación Emocional",
    category: "books",
    careCategory: "childcare",
    categoryLabelEs: "Libros & Emociones",
    categoryLabelEn: "Books & Feelings",
    targetMinAge: 2,
    targetMaxAge: 6,
    ageBadge: "2 - 6 years",
    ageBadgeEs: "2 - 6 años",
    description: "Visual masterpiece helping toddlers and preschoolers identify and express anger, calm, fear, and joy.",
    descriptionEs: "Clásico recomendado por psicólogos infantiles para ayudar a los niños a poner nombre y color a sus emociones y superar rabietas.",
    pedagogicalBenefitEs: "Especialmente útil para que niñeras y padres sincronicen técnicas de co-regulación emocional.",
    pedagogicalBenefitEn: "Ideal for caregivers to practice emotional labeling and tantrum prevention.",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=the+color+monster+book&tag=matchcaring-20",
    priceEstimate: "$18.50",
    rating: 4.9,
    reviewCount: 3890,
    badge: "Must-Have",
    badgeEs: "Imprescindible",
  },
  {
    id: "prod_silicone_feeding_set",
    title: "100% Food-Grade Silicone Suction Plates & Cutlery",
    titleEs: "Set de Alimentación BLW en Silicona Platino Antideslizante",
    category: "daily_use",
    careCategory: "childcare",
    categoryLabelEs: "Uso Diario & Comidas",
    categoryLabelEn: "Daily Use & Feeding",
    targetMinAge: 0,
    targetMaxAge: 4,
    ageBadge: "6m - 4 years",
    ageBadgeEs: "6m - 4 años",
    description: "High-suction grip plate prevents bowl-flipping tantrums during meal times while teaching self-feeding.",
    descriptionEs: "Plato con potente succión antideslizante y cubiertos ergonómicos suaves con las encías. Apto para lavavajillas y microondas.",
    pedagogicalBenefitEs: "Reduce el estrés de comidas compartidas y estimula la autoalimentación (Baby-Led Weaning).",
    pedagogicalBenefitEn: "Supports self-led feeding and reduces mealtime spills and clean-up stress.",
    imageUrl: "https://images.unsplash.com/photo-1617331140180-e8262094733a?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=silicone+baby+feeding+set+suction&tag=matchcaring-20",
    priceEstimate: "$24.90",
    rating: 4.8,
    reviewCount: 950,
    badge: "Parent Approved",
    badgeEs: "Fácil Limpieza",
  },
  {
    id: "prod_lifevac_anti_choking",
    title: "LifeVac Anti-Choking Home Rescue Device Kit",
    titleEs: "LifeVac: Dispositivo de Succión para Emergencias de Asfixia",
    category: "safety",
    careCategory: "childcare",
    categoryLabelEs: "Seguridad & Emergencias",
    categoryLabelEn: "Safety & Emergency",
    targetMinAge: 1,
    targetMaxAge: 120,
    ageBadge: "Para toda la familia",
    ageBadgeEs: "Para toda la familia",
    description: "Clinically proven non-invasive suction apparatus designed to clear airway obstructions when Heimlich maneuver fails.",
    descriptionEs: "Dispositivo médico portátil no invasivo con mascarillas pediátricas y de adulto. Diseñado para desobstruir vías aéreas en segundos.",
    pedagogicalBenefitEs: "Tranquilidad crítica en el hogar para cuidadores, niñeras y abuelos ante riesgo de asfixia.",
    pedagogicalBenefitEn: "Life-saving emergency kit for childcare providers and household first-aid stations.",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=lifevac+choking+rescue+device&tag=matchcaring-20",
    priceEstimate: "$69.95",
    rating: 4.9,
    reviewCount: 8200,
    badge: "Medical Grade",
    badgeEs: "Seguridad Crítica",
  },
  {
    id: "prod_white_noise_shusher",
    title: "Portable Rechargeable White Noise Machine for Nap Routines",
    titleEs: "Máquina Portátil de Ruido Blanco y Sonidos Relajantes para Siestas",
    category: "daily_use",
    careCategory: "childcare",
    categoryLabelEs: "Rutinas & Sueño",
    categoryLabelEn: "Sleep & Routines",
    targetMinAge: 0,
    targetMaxAge: 4,
    ageBadge: "0 - 4 years",
    ageBadgeEs: "0 - 4 años",
    description: "Compact travel sound soother with 21 soothing sounds including womb, rain, and shush tones.",
    descriptionEs: "Sonidos continuos y temporizador de apagado. Bloquea ruidos externos de la calle para mantener la siesta del infante.",
    pedagogicalBenefitEs: "Estandariza la rutina de siestas para que cualquier niñera o cuidador logre dormir al bebé rápidamente.",
    pedagogicalBenefitEn: "Helps maintain predictable nap routines across different caregivers.",
    imageUrl: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=portable+white+noise+machine+baby&tag=matchcaring-20",
    priceEstimate: "$22.99",
    rating: 4.8,
    reviewCount: 2310,
    badge: "Sleep Saver",
    badgeEs: "Sueño Seguro",
  },
  {
    id: "prod_sensory_kinetic_sand",
    title: "Kinetic Sensory Sand Kit with Inflatable Play Tray",
    titleEs: "Kit de Arena Sensorial Cinética Mágica con Bandeja de Juego",
    category: "activities",
    careCategory: "childcare",
    categoryLabelEs: "Sensorial & Motricidad",
    categoryLabelEn: "Sensory & Play",
    targetMinAge: 2,
    targetMaxAge: 7,
    ageBadge: "3 - 7 years",
    ageBadgeEs: "3 - 7 años",
    description: "Hypoallergenic indoor sensory play that never dries out and cleans easily without sticking to skin.",
    descriptionEs: "Arena moldeable 100% no tóxica para juegos de mesa. No mancha, se limpia en segundos y relaja la ansiedad en tardes en casa.",
    pedagogicalBenefitEs: "Excelente actividad para mantener al niño enfocado durante 45+ minutos bajo supervisión de la niñera.",
    pedagogicalBenefitEn: "High-engagement calming play activity for afternoons with nanny.",
    imageUrl: "https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=kinetic+sand+sensory+kit&tag=matchcaring-20",
    priceEstimate: "$19.99",
    rating: 4.7,
    reviewCount: 4120,
    badge: "Bestseller",
    badgeEs: "Más Vendido",
  },

  // ==========================================
  // 2. ELDERLY CARE (Adultos Mayores / Gerontología)
  // ==========================================
  {
    id: "prod_smart_pill_dispenser",
    title: "Smart Weekly Pill Organizer with Audio Alarm & Flashing Alerts",
    titleEs: "Pastillero Electrónico Inteligente con Alarma Sonora y Recordatorio",
    category: "elderly",
    careCategory: "elderly_care",
    categoryLabelEs: "Medicamentos & Salud",
    categoryLabelEn: "Medication & Health",
    targetMinAge: 60,
    targetMaxAge: 120,
    ageBadge: "60+ years",
    ageBadgeEs: "60+ años",
    description: "Prevents missed doses or double-medication with loud audio prompts and compartment locking for seniors.",
    descriptionEs: "Evita olvidos y sobredosis. Emite alarmas sonoras y luces en cada toma programada. Ideal para supervisión de cuidadores.",
    pedagogicalBenefitEs: "Garantiza el 100% de adherencia médica prescrita sin estrés para el paciente ni la cuidadora.",
    pedagogicalBenefitEn: "Ensures 100% medication schedule adherence without stress.",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=automatic+pill+dispenser+elderly&tag=matchcaring-20",
    priceEstimate: "$39.99",
    rating: 4.8,
    reviewCount: 3100,
    badge: "Essential Care",
    badgeEs: "Cuidado Esencial",
  },
  {
    id: "prod_fall_prevention_nightlight",
    title: "Automatic Motion Sensor LED Night Lights for Bedside & Hallways",
    titleEs: "Luces LED con Sensor de Movimiento Anti-Caídas para Cama y Baño",
    category: "safety",
    careCategory: "elderly_care",
    categoryLabelEs: "Seguridad & Anti-Caídas",
    categoryLabelEn: "Safety & Fall Prevention",
    targetMinAge: 60,
    targetMaxAge: 120,
    ageBadge: "60+ years",
    ageBadgeEs: "60+ años",
    description: "Warm glow automatic path lighting activating on footsteps to prevent disoriented night falls in seniors.",
    descriptionEs: "Ilumina suavemente el paso al levantarse al baño de noche sin deslumbrar. Previene tropiezos y desorientación.",
    pedagogicalBenefitEs: "Protocolo recomendado por geriatras para mantener la orientación espacial nocturna.",
    pedagogicalBenefitEn: "Geriatrician-recommended protocol for night-time spatial orientation.",
    imageUrl: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=motion+sensor+night+light+elderly&tag=matchcaring-20",
    priceEstimate: "$21.99",
    rating: 4.9,
    reviewCount: 5400,
    badge: "Fall Safety",
    badgeEs: "Prevención Caídas",
  },
  {
    id: "prod_omron_bp_monitor",
    title: "Clinically Validated Upper Arm Digital Blood Pressure Monitor",
    titleEs: "Tensiómetro Digital de Brazo con Detección de Arritmias Clínico",
    category: "elderly",
    careCategory: "elderly_care",
    categoryLabelEs: "Signos Vitales",
    categoryLabelEn: "Vital Signs",
    targetMinAge: 50,
    targetMaxAge: 120,
    ageBadge: "50+ years",
    ageBadgeEs: "50+ años",
    description: "One-touch accurate blood pressure and pulse tracking with oversized high-contrast display.",
    descriptionEs: "Medición rápida y precisa de presión arterial con números gigantes de fácil lectura para cuidadoras y abuelos.",
    pedagogicalBenefitEs: "Facilita la bitácora diaria de signos vitales para reportes semanales al médico de cabecera.",
    pedagogicalBenefitEn: "Enables seamless daily vitals logging for family and doctor updates.",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=omron+blood+pressure+monitor&tag=matchcaring-20",
    priceEstimate: "$49.50",
    rating: 4.9,
    reviewCount: 12500,
    badge: "Clinical Standard",
    badgeEs: "Estándar Clínico",
  },

  // ==========================================
  // 3. DISABILITY & SPECIAL NEEDS (Discapacidad / TEA)
  // ==========================================
  {
    id: "prod_weighted_sensory_blanket",
    title: "Therapeutic Weighted Blanket for Sensory Overload & Autism (TEA)",
    titleEs: "Manta Sensorial de Presión Profunda para Regulación Emocional y TEA",
    category: "disability",
    careCategory: "disability_care",
    categoryLabelEs: "Regulación Sensorial",
    categoryLabelEn: "Sensory Regulation",
    targetMinAge: 3,
    targetMaxAge: 120,
    ageBadge: "Todas las edades",
    ageBadgeEs: "Todas las edades",
    description: "Deep pressure touch stimulation blanket engineered to reduce cortisol and ground nervous system during sensory crises.",
    descriptionEs: "Estimulación de presión profunda no invasiva. Ayuda a calmar crisis de sobrecarga sensorial, ansiedad o insomnio.",
    pedagogicalBenefitEs: "Herramienta primaria de desescalada recomendada en protocolos de neurodiversidad sin restricción física.",
    pedagogicalBenefitEn: "Primary de-escalation tool for neurodiverse care without physical restriction.",
    imageUrl: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=weighted+blanket+sensory&tag=matchcaring-20",
    priceEstimate: "$45.00",
    rating: 4.8,
    reviewCount: 7800,
    badge: "Therapist Pick",
    badgeEs: "Recomendado TEA",
  },
  {
    id: "prod_aac_pictogram_board",
    title: "Visual AAC Schedule & Communication Board with Waterproof Pictograms",
    titleEs: "Tablero de Comunicación Aumentativa (SAAC) con 120 Pictogramas",
    category: "disability",
    careCategory: "disability_care",
    categoryLabelEs: "Comunicación Aumentativa",
    categoryLabelEn: "Augmentative Communication",
    targetMinAge: 2,
    targetMaxAge: 120,
    ageBadge: "Todas las edades",
    ageBadgeEs: "Todas las edades",
    description: "Visual cue cards allowing non-verbal children and adults to express pain, food, bathroom, and emotional states.",
    descriptionEs: "Tarjetas plastificadas con velcro para que personas no verbales expresen dolor, hambre, baño o emociones con facilidad.",
    pedagogicalBenefitEs: "Disminuye la frustración conductual hasta en un 80% al proveer un canal de comunicación directo con la cuidadora.",
    pedagogicalBenefitEn: "Reduces behavioral frustration by up to 80% by establishing direct communication with caregiver.",
    imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://www.amazon.com/s?k=aac+visual+communication+cards&tag=matchcaring-20",
    priceEstimate: "$26.90",
    rating: 4.9,
    reviewCount: 1980,
    badge: "Essential AAC",
    badgeEs: "Comunicación Esencial",
  },
];

export function getRecommendedProducts(
  childAge?: number,
  category?: string,
  careCategory?: CareCategory | "all"
): RecommendedProduct[] {
  let list = RECOMMENDED_PRODUCTS;

  if (category && category !== "all") {
    list = list.filter((p) => p.category === category);
  }

  // Filter or prioritize based on careCategory
  if (careCategory && careCategory !== "all") {
    const matching = list.filter((p) => p.careCategory === careCategory || !p.careCategory);
    if (matching.length > 0) {
      list = matching;
    }
  }

  if (childAge !== undefined && childAge !== null) {
    // Sort items matching target age range first
    list = [...list].sort((a, b) => {
      const aMatches = childAge >= a.targetMinAge && childAge <= a.targetMaxAge ? 1 : 0;
      const bMatches = childAge >= b.targetMinAge && childAge <= b.targetMaxAge ? 1 : 0;
      return bMatches - aMatches;
    });
  }

  return list;
}
